# Generated by Django 4.0.3 on 2022-09-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.TextField(blank=True, help_text='(optional)', null=True)),
                ('title', models.TextField(blank=True, help_text='(optional)', null=True)),
                ('descendants', models.IntegerField(blank=True, help_text='Total Comment count', null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(choices=[('story', 'Story'), ('comment', 'Comment'), ('poll', 'Poll'), ('job', 'Job'), ('pollopt', 'Poll option'), ('other', 'other')], default='story', help_text='Enter either one of Job, Story, Comment, Poll or Poll option', max_length=255)),
                ('text', models.TextField(blank=True, help_text='The comment, story or poll text.(optional)', null=True)),
                ('url', models.URLField(blank=True, help_text='(optional)', null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('classification', models.CharField(default='HackerNews', max_length=255)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.TextField(blank=True, help_text='Name of commenter', null=True)),
                ('comment', models.TextField(blank=True, help_text='Write your comment here', null=True)),
                ('type', models.CharField(default='comment', max_length=255)),
                ('classification', models.CharField(default='HackerNews comment', max_length=255)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news_app.news')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
